// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RotaDeViagem.Infra.Data.Context;

#nullable disable

namespace RotaDeViagem.Infra.Data.Migrations
{
    [DbContext(typeof(RotaDeViagemDbContext))]
    [Migration("20250617000757_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RotaDeViagem.Domain.Entities.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Rotas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("396822c5-ca79-4ea0-a1a1-a6fb8b54561f"),
                            Destino = "BRC",
                            Origem = "GRU",
                            Valor = 10m
                        },
                        new
                        {
                            Id = new Guid("30977f26-5eef-4fd6-9688-4d8c076f54b9"),
                            Destino = "SCL",
                            Origem = "BRC",
                            Valor = 10m
                        },
                        new
                        {
                            Id = new Guid("aac4c8e7-3f93-4686-b35e-948571f9b98d"),
                            Destino = "CDG",
                            Origem = "GRU",
                            Valor = 75m
                        },
                        new
                        {
                            Id = new Guid("a3501db8-cee8-49e8-a9c2-b1141467c057"),
                            Destino = "SCL",
                            Origem = "GRU",
                            Valor = 75m
                        },
                        new
                        {
                            Id = new Guid("3a9dacca-b4de-4045-882c-c400caa30be0"),
                            Destino = "ORL",
                            Origem = "GRU",
                            Valor = 56m
                        },
                        new
                        {
                            Id = new Guid("c3e19a3b-1eed-4fe8-b130-20291131940b"),
                            Destino = "CDG",
                            Origem = "ORL",
                            Valor = 5m
                        },
                        new
                        {
                            Id = new Guid("3a50f582-6541-4f81-8117-4d5e1db789be"),
                            Destino = "ORL",
                            Origem = "SCL",
                            Valor = 20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
